In [1]:
#Importing the pandas module
import pandas as pd

In [2]:
#Loading the dataset
dataframe = pd.read_csv('raw_dataset.csv')

In [3]:
#setting up the custom number of rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
#Checking the datatypes of all the columns inside the dataset
dataframe.dtypes

Rank                                 int64
Peak                                object
All Time Peak                       object
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
Ref.                                object
dtype: object

In [5]:
dataframe.columns = dataframe.columns.str.strip('.').str.replace(r'\xa0', ' ', regex = True)
dataframe.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref'],
      dtype='object')

In [6]:
#Replacing the unwanted data to a clean data for all the columns.
dataframe['Peak'] = dataframe['Peak'].str.replace(r'\[.*\]', '', regex = True)
dataframe['All Time Peak'] = dataframe['All Time Peak'].str.replace(r'\[.*\]', '', regex= True)

In [7]:
#Replacing the unwanted data to a clean data for Actual gross column.

dataframe['Actual gross'] = dataframe['Actual gross'].str.lstrip('$').str.replace(r',|\[.*\]', '', regex = True)

In [8]:
#Replacing the unwanted data to a clean data for 'Adjusted gross (in 2022 dollars)' column.
dataframe['Adjusted gross (in 2022 dollars)'] = dataframe['Adjusted gross (in 2022 dollars)'].str.lstrip('$').str.replace(',', '', regex = False)

In [9]:
#Replacing the unwanted data to a clean data for 'Your title' column.
dataframe['Tour title'] = dataframe['Tour title'].str.replace(r'†|‡|\[.*\]|\[.*\]|\*', '', regex = True)

In [10]:
#Replacing the unwanted data to a clean data for 'Average gross' column.
dataframe['Average gross'] = dataframe['Average gross'].str.replace(r'\$|,', '', regex = True)
dataframe

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,[26]

In [11]:
#Replacing the unwanted data to a clean data for 'Ref' column.
dataframe['Ref'] = dataframe['Ref'].replace(r'\[|\]|[a-z]', '', regex = True)

In [12]:
#Displaying the dataset
dataframe.head(8)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,1
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,3
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,6
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,7
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,8
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,9
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,11
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927,12

In [13]:
#Changing the data type of multiple columns like peak, all time peak and ref
dataframe['Peak'] = pd.to_numeric(dataframe['Peak'], errors = 'coerce')
dataframe['All Time Peak'] = pd.to_numeric(dataframe['All Time Peak'], errors = 'coerce')
dataframe['Ref'] = pd.to_numeric(dataframe['Ref'], errors = 'coerce')

In [14]:
#Replcing the null values in the columns for a relevant data
dataframe['Peak'] = dataframe['Peak'].fillna(dataframe['Peak'].median())
dataframe['All Time Peak'] = dataframe['All Time Peak'].fillna(dataframe['All Time Peak'].median())
dataframe['Ref'] = dataframe['Ref'].fillna(dataframe['Ref'].median())

In [15]:
dataframe.rename(columns = {'Ref': 'Reference', 'Actual gross' : 'Actual_Gross'}, inplace = True)

In [16]:
dataframe['Actual_Gross'] = pd.to_numeric(dataframe['Actual_Gross'], errors = 'coerce')

In [19]:
VAT = 0.13
dataframe['Actual_Gross_with_VAT'] = dataframe['Actual_Gross'] * VAT

In [25]:
#Spliting the Years column into two different columns
dataframe[['Starting_Year', 'Ending_Year']] = dataframe['Year(s)'].str.extractall(r'(\d{4})').unstack()

In [31]:
#Dropping the Year(s) table after i have splitted it to new columns
dataframe.drop(columns = 'Year(s)', inplace = True)

In [32]:
dataframe

,Rank,Peak,All Time Peak,Actual_Gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Shows,Average gross,Reference,Actual_Gross_with_VAT,Ending_Year,Starting_Year
0,1,1.0,2.0,780000000,780000000,Taylor Swift,The Eras Tour,56,13928571,1.0,1.014000e+08,2024,2023
1,2,1.0,7.0,579800000,579800000,Beyoncé,Renaissance World Tour,56,10353571,3.0,7.537400e+07,NaN,2023
2,3,1.0,2.0,411000000,560622615,Madonna,Sticky & Sweet Tour,85,4835294,6.0,5.343000e+07,2009,2008
3,4,2.0,10.0,397300000,454751555,Pink,Beautiful Trauma World Tour,156,2546795,7.0,5.164900e+07,2019,2018
4,5,2.0,8.5,345675146,402844849,Taylor Swift,Reputation Stadium Tour,53,6522173,8.0,4.493777e+07,NaN,2018
5,6,2.0,10.0,305158363,388978496,Madonna,The MDNA Tour,88,3467709,9.0,3.967059e+07,NaN,2012
6,7,2.0,8.5,280000000,381932682,Celine Dion,Taking Chances World Tour,131,2137405,11.0,3.640000e+07,2009,2008
7,7,2.0,8.5,257600000,257600000,Pink,Summer Carnival,41,6282927,12.0,3.348800e+07,2024,2023
8,9,2.0,8.5,256084556,312258401,Beyoncé,The Formation World Tour,49,5226215,13.0,3.329099e+07,NaN,2016
9,10,2.0,8.5,250400000,309141878,Taylor Swift,The 1989 World Tour,85,2945882,14.0,3.255200e+07,NaN,2015
10,11,2.0,8.5,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,132,1735606,1516.0,2.978300e+07,2014,2013
11,12,2.0,14.0,227400000,295301479,Lady Gaga,The Monster Ball Tour,203,1118227,18.0,2.956200e+07,2011,2009
12,13,2.0,8.5,204000000,251856802,Katy Perry,Prismatic World Tour,151,1350993,19.0,2.652000e+07,2015,2014
13,14,1.0,8.5,200000000,299676265,Cher,Living Proof: The Farewell Tour,325,615385,20.0,2.600000e+07,2005,2002
14,15,2.0,8.5,194000000,281617035,Madonna,Confessions Tour,60,3233333,5.0,2.522000e+07,NaN,2006
15,16,2.0,8.5,184000000,227452347,Pink,The Truth About Love Tour,142,1295775,22.0,2.392000e+07,2014,2013
16,17,2.0,8.5,170000000,213568571,Lady Gaga,Born This Way Ball,98,1734694,12.0,2.210000e+07,2013,2012
17,18,2.0,8.5,169800000,207046755,Madonna,Rebel Heart Tour,82,2070732,4.0,2.207400e+07,2016,2015
18,19,2.0,8.5,167700000,204486106,Adele,Adele Live 2016,121,1385950,25.0,2.180100e+07,2017,2016
19,20,2.0,8.5,150000000,185423109,Taylor Swift,The Red Tour,86,1744186,26.0,1.950000e+07,2014,2013