In [132]:
#Importing the pandas module
import pandas as pd

In [133]:
#Loading the dataset
dataframe = pd.read_csv('raw_dataset.csv')

In [47]:
#setting up the custom number of rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [48]:
#Diaplaying the dataset
dataframe

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [49]:
#Checking the datatypes of all the columns inside the dataset
dataframe.dtypes

Rank                                 int64
Peak                                object
All Time Peak                       object
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
Ref.                                object
dtype: object

In [142]:
dataframe.columns = dataframe.columns.str.strip().str.replace('.', '')
dataframe.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref'],
      dtype='object')

In [143]:
#Replacing the unwanted data to a clean data for all the columns.
dataframe['Peak'] = dataframe['Peak'].str.replace(r'\[.*\]', '', regex = True)
dataframe['All Time Peak'] = dataframe['All Time Peak'].str.replace(r'\[.*\]', '', regex= True)

In [144]:
#Replacing the unwanted data to a clean data for Actual gross column.
Actual_Gross = dataframe.columns[3]
dataframe[Actual_Gross] = dataframe[Actual_Gross].str.lstrip('$').str.replace(r',|\[.*\]', '', regex = True)

In [145]:
#Replacing the unwanted data to a clean data for 'Adjusted gross (in 2022 dollars)' column.
dataframe['Adjusted gross (in 2022 dollars)'] = dataframe['Adjusted gross (in 2022 dollars)'].str.lstrip('$').str.replace(',', '', regex = False)

In [146]:
#Replacing the unwanted data to a clean data for 'Your title' column.
dataframe['Tour title'] = dataframe['Tour title'].str.replace(r'†|‡|\[.*\]|\[.*\]|\*', '', regex = True)

In [147]:
#Replacing the unwanted data to a clean data for 'Average gross' column.
dataframe['Average gross'] = dataframe['Average gross'].str.replace(r'\$|,', '', regex = True)

In [154]:
#Replacing the unwanted data to a clean data for 'Ref' column.
dataframe['Ref'] = dataframe['Ref'].replace(r'\[|\]|[a-z]', '', regex = True)

In [156]:
dataframe

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,1
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,3
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,6
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,7
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,8
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,9
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,11
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927,12
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,13
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,14
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,1516
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227,18
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,19
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385,20
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,5
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,22
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,4
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,25
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,26